---
- name: Configure Petclinic CICD Agent Service
  hosts: buildservers
  become: yes

  vars:
    jenkins_url: "{{ lookup('env', 'JENKINS_URL') }}"
    jenkins_secret: "{{ lookup('env', 'JENKINS_SECRET') }}"
    jenkins_agent_name: "petclinic-cicd"
    jenkins_agent_workdir: "/usr/local/jenkins-service"

  tasks:
    - name: Ensure Java is installed
      ansible.builtin.package:
        name: openjdk-17-jdk-headless
        state: present

    - name: Create Jenkins agent working directory
      ansible.builtin.file:
        path: "{{ jenkins_agent_workdir }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Download agent.jar from Jenkins controller
      ansible.builtin.get_url:
        url: "{{ jenkins_url }}/jnlpJars/agent.jar"
        dest: "{{ jenkins_agent_workdir }}/agent.jar"
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Create start-agent.sh script
      ansible.builtin.template:
        src: start-agent.sh.j2
        dest: "{{ jenkins_agent_workdir }}/start-agent.sh"
        owner: ubuntu
        group: ubuntu
        mode: '0755'
      vars:
        url: "{{ jenkins_url }}"
        secret: "{{ jenkins_secret }}"
        agent_name: "{{ jenkins_agent_name }}"
        agent_workdir: "{{ jenkins_agent_workdir }}"

    - name: Create systemd service file for Jenkins Agent
      ansible.builtin.template:
        src: petclinic-cicd.service.j2
        dest: /etc/systemd/system/petclinic-cicd.service
        owner: root
        group: root
        mode: '0644'
      vars:
        agent_workdir: "{{ jenkins_agent_workdir }}"

    - name: Reload systemd daemon
      ansible.builtin.command: systemctl daemon-reload
      notify:
        - Restart petclinic-cicd service

    - name: Enable petclinic-cicd service
      ansible.builtin.service:
        name: petclinic-cicd
        enabled: yes
        state: started

  handlers:
    - name: Restart petclinic-cicd service
      ansible.builtin.service:
        name: petclinic-cicd
        state: restarted
