---
- hosts: webservers
  become: yes
  vars:
    petclinic_repo: 'https://github.com/JustFiesta/spring-petclinic.git'
    repo_directory: '/src/spring-petclinic-repo'
  tasks:
    - name: Git checkout
      git:
        repo: "{{ petclinic_repo }}"
        dest: "{{ repo_directory}}"
        clone: true
        force: yes

    - name: Set fact from workstation environment
      set_fact:
        rds_db_value: "{{ lookup('env', 'RDS_DB') }}"
      delegate_to: localhost

    - name: Set RDS_DB environment variable on hosts
      shell: 'export RDS_DB=$RDS_DB'
      environment:
        RDS_DB: "{{ rds_db_value }}"

    - name: Pull newest image
      shell: 'docker compose pull'
      args:
        chdir: "{{ repo_directory}}"

    - name: Take down application with docker compose
      shell: 'docker compose down'
      args:
        chdir: "{{ repo_directory}}"

    - name: Deploy application with docker compose
      shell: 'docker compose up -d'
      args:
        chdir: "{{ repo_directory}}"
    
    - name: Prune docker system
      shell: 'docker system prune -f'