---
- hosts: webservers
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name: 
          - ca-certificates
          - curl
        state: present

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt cache after adding Docker repo
      apt:
        update_cache: yes

    - name: Install Docker and Java
      apt:
        name: 
          - docker-ce
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - openjdk-21-jre-headless
        state: latest
      notify: restart docker

    - name: Ensure docker group exists
      group:
        name: docker
        state: present

    - name: Add user to docker group
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes
  
  handlers:
    - name: Start and enable Docker service
      systemd:
        name: docker
        state: restarted
        enabled: yes
      listen: restart docker

- hosts: buildservers
  become: true
  tasks:
    - name: Install Jenkins and Java - buildservers
      package:
        name:
          - openjdk-21-jre-headless
          - jenkins
        state: latest
      notify: restart jenkins

  handlers:
    - name: Jenkins restart
      systemd:
        name: jenkins
        state: restarted
        enabled: yes
      listen: restart jenkins