webservers:
  hosts:
    app-a:
      ansible_host: 34.245.11.156
      ansible_ssh_private_key_file: ~/.ssh/mbocak_key_capstone.pem
    app-b:
      ansible_host: 34.253.222.191
      ansible_ssh_private_key_file: ~/.ssh/mbocak_key_capstone.pem
buildservers:
  hosts:
    jenkins-a:
      ansible_host: 18.201.130.30
      ansible_ssh_private_key_file: ~/.ssh/mbocak_key_capstone.pem