webservers:
  hosts:
    app-a:
      ansible_hosts: 18.202.244.102
      ansible_ssh_private_key_file: ~/.ssh/mbocak_key.pem
    app-b:
      ansible_hosts: 34.243.248.106
      ansible_ssh_private_key_file: ~/.ssh/mbocak_key.pem
buildservers:
  hosts:
    jenkins-a:
      ansible_hosts: 3.249.73.92
      ansible_ssh_private_key_file: ~/.ssh/mbocak_key.pem